### ISSUE TITLE
Use renovate (-greenkeeper-)

### ISSUE THREAD

**Issue by blatinier** [blatinier/onestpasdespigeons#22]
Greenkeeper is an helper for automatic updates of npm packages. 
It tries to upgrade a package, run tests and either open an issue or send a PR

See if it's OK to use with yarn.

https://greenkeeper.io

**Comment by Far3t** [comment]
Something like that to use with yarn: https://gist.github.com/maxrimue/16e272c4e0b8a8ac9dd5570e180e08c0

**Comment by blatinier** [comment]
Greenkeeper 2 supports yarn. houray!

**Comment by blatinier** [comment]
Greenkeeper does not handle package.json files in subdirs.
This does: 
https://github.com/singapore/renovate

**Comment by blatinier** [comment]
Yay! It works! (cf #96 its first PR!!! :) )
