### ISSUE TITLE
Possibility to add a measure on a product not in the db

### ISSUE THREAD

**Issue by Far3t** [blatinier/onestpasdespigeons#68]
Be able to add a product?
Manual validation on this side?

Maybe find other product-databases opensource we can get.

**Comment by blatinier** [comment]
What workflow? 
- Page to add product + page to add measure
- Page to add measure → little btn "product not found" → popup/dropdown (replacing the search field) to add product
- Both??

**Comment by Far3t** [comment]
I would rather prefer the second option. More obvious for the user who just wanted to add a new measure and who could not find the product he measured.
