### ISSUE TITLE
Add nickname to User

### ISSUE THREAD

**Issue by Far3t** [blatinier/onestpasdespigeons#94]
Instead of having the username, coming from the register form or SSO (Google, Facebook, ...), it could be easier for the user to set a nickname for people to see them.

**Comment by blatinier** [comment]
We should:
- [ ] default nickname to username at first
- [ ] lock username for SSO users
- [ ] make username modified on nickname modification for non-SSO users
- [ ] Show only nickname field in all forms

@Far3t validation? :)
